# Generated by Django 5.0.6 on 2024-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=400)),
                ('last', models.CharField(blank=True, max_length=400)),
                ('img', models.ImageField(upload_to='pfps')),
            ],
        ),
    ]
